fix panics during Scans when there are no layers
goharbor/harbor-scanner-clair pull request #25
Opened 2021-10-06 01:33 UTC by tariq1890

2021-10-07 08:20 UTC, danielpacak requested changes
Thank you for this PR @tariq1890 I left one suggestion.

Notice that we have to update CI validation workflow and probably migrate from Travis CI to GitHub Actions before we can merge your changes. I'll let you know to rebase your branch.

2021-10-07 08:20 UTC, danielpacak commented on pkg/scanner/adapter.go
> +		return harbor.ScanReport{}, nil
The report returned here is parsed by Harbor service so even if there are no vulnerabilities we must return required metadata:

```suggestion
		return harbor.ScanReport{
			GeneratedAt:     time.Now(),
			Scanner:         etc.GetScannerMetadata(),
			Artifact:        req.Artifact,
			Severity:        harbor.SevUnknown,
			Vulnerabilities: []harbor.VulnerabilityItem{},
		}, nil
```

2021-10-09 18:59 UTC, tariq1890 commented
Thanks a lot @danielpacak . I've committed your suggestions

2021-10-13 10:02 UTC, danielpacak approved these changes

2023-08-22 07:33 UTC, closed without merging